spring.application.name=E-commerce-System
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system
spring.datasource.password=dbms123

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# ===============================
# JPA CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# JWT CONFIG
# ===============================
jwt.default-role=ROLE_USER
jwt.expiration=86400000
jwt.secret=MySuperStrongSecretKey123456789

# ===============================
# STRIPE
# ===============================
#stripe.secret.key=your_stripe_secret_key

spring.devtools.restart.enabled=true

logging.level.org.springframework.security=DEBUG

